# Use an official PHP image
FROM php:7.4-cli

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container
COPY . .

# Expose the port the server will run on
EXPOSE 3002

# Use the PHP CLI's built-in server to serve the application
CMD [ "php", "-S", "0.0.0.0:3002" ]